# User Settings | Edit there as per required

title: Like the ceiling can't hold us
url: "https://jiawei1996.github.io"
# baseurl: "/accent"

# This will show up at the top of index page
site_heading: >
    foo <span class="faded">Jiawei's blog</span>

email: cuijiawei.cn@gmail.com
author: Jiawei,崔家维
# This description will show up in google search results
# (for index page) etc.
description: 我的博客,一个分享交流的平台 --崔家维~Glad to see you ,this is my blog and there might be some web or other ideas to share.--jiawei

# This will what will show against &copy; in the footer
copyright: jiawei
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
# intro: false         
# Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>Jiawei's Blog</span>, a place where there are some web skills & ideas to share.

# permalink: /:title.html

# Comments are powered by disqus
# comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
# about_stub: >
#     Keep this sentence less than 13 words or it won't look good.

about_footer: true

# twitter_username: AnkitSultana
github_username: jiawei1996
# facebook_id: yourusername

# favicon: true
# favicon_location: "images/favicon.ico"

# profile_picture: images/temp.png
# paginate: 5
# paginate_path: "/page/:num"
# tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
# og_image: "images/accent.png" # This will show in facebook thumbnails
# twitter_image: "http://ankitsultana.me/images/accent.png?1234" # This will show in twitter cards


highlighter: rouge
highlight: true

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

# gems:
#     - jekyll-paginate

# sass:
#     style: compressed
#     sass_dir: _sass

# Scopes
# defaults:
#     -
#         scope:
#             path:   ""
#             type:   "pages"
#         values:
#             layout: "page"
#     -
#         scope:
#             path:   ""
#             type:   "posts"
#         values:
#             layout: "post"

# exclude: [vendor] # For travis ci
